### ISSUE TITLE
member resource

### ISSUE THREAD

**Issue by nhomble** [camunda-community-hub/terraform-provider-camunda#116]
https://console.cloud.camunda.io/customer-api/openapi/docs/#/

Looks like there's good enough crud with the `members/` api. Ideally I think a 1:1 member:resource relationship would be good for onboarding teammates.

Any reason not to incorporate this?

**Comment by multani** [comment]
Hey @nhomble,

Being able to manage member would be a great additional resource to add! :+1: 

I will try to check this in the coming weeks.

**Comment by multani** [comment]
Hey @nhomble,

I released [`camunda_organization_member`](https://registry.terraform.io/providers/camunda-community-hub/camunda/latest/docs/resources/organization_member) in [v0.0.10](https://github.com/camunda-community-hub/terraform-provider-camunda/releases/tag/v0.0.10) :wave:
