### ISSUE TITLE
Handle client credentials scope

### ISSUE THREAD

**Issue by fdebuire** [camunda-community-hub/terraform-provider-camunda#80]
Using the provider we can handle client credentials using the resource `camunda_cluster_client`, however the scopes are not configurable even though they are in the UI.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/50776984/227536297-bf015ec1-df66-4f40-a641-a3c2b80d024f.png">

By default the provider will grant all the scopes on a created client credentials which could be a security issue.

**Comment by multani** [comment]
@fdebuire [the API](https://console.cloud.camunda.io/customer-api/openapi/docs/#/default/CreateClient) doesn't expose the ability to set scopes at the moment, but that would be great to have them configurable once this is available there :+1:

**Comment by fdebuire** [comment]
@multani Thanks for the answer, is there any github for the API where we can create an issue, or should we make a feature request using the support?

**Comment by multani** [comment]
I don't think we have a GitHub repository for this API, so feel free to open a feature request if you are interested :)

I've raised the need internally, but it would get more visibility if it comes from an external user :+1:

**Comment by multani** [comment]
@fdebuire FYI, the API should soon allow to configure the scopes: https://github.com/camunda/issues/issues/158

**Comment by fdebuire** [comment]
Hello @multani, the support informed us that the API has been enriched and pushed to production. I can see the new field `permissions` here https://console.cloud.camunda.io/customer-api/openapi/docs/#/default/CreateClient

**Comment by multani** [comment]
I'll take a look in a couple of weeks after my holidays 🚀

**Comment by multani** [comment]
@fdebuire I released [v0.0.6](https://github.com/camunda-community-hub/terraform-provider-camunda/releases/tag/v0.0.6) with the new client scopes configuration feature.

Note that, contrary to the UI, it's not possible to create a client with no scopes at the moment. This may change in the future when this has been clarified with the upstream team.
